create table products(
                         id number generated by default as identity,
                         productName varchar2(256),
                         quantity Integer,
                         color varchar2(256),
                         brand varchar2(256),
                         imageFile varchar2(1024),
                         price VARCHAR2(256)
);
